### ISSUE TITLE
refactor the PDU management commands

### ISSUE THREAD

**Issue by parmentelat** [fit-r2lab/rhubarbe#16]
# goals

* to replace the hard-coded commands like `on-jaguar` and similar with something that is more scalable
* to take into account the second PDU-based devices in C007
* and so, to come up with a declarative way to define the configuration

# expected behaviour

and so we will replace the `rhubarbe-script` thingy with a more adequate `rhubarbe-pdu` command; see expected behaviour below

## returncode

generally speaking:
* 255 means there's a failure
* 0 means everything went well
* 1 is reserved for the `status` command and means the device is turned OFF

# config files

a new file in `/etc/rhubarbe/inventory-pdus.yaml` will allow to describe the location and addresses of hardware

**Comment by parmentelat** [comment]
# todo

- [x] replace the `script` main subcommand with `pdu`
- [x] write `inventory_pdus.py`
- [x] make code more asynchronous
- [ ] remove most of the scripts under `rhubarbe/scripts`, except for `pdu` (this will maybe one day be written in async pexpect, but that's a separate issue)

**Comment by parmentelat** [comment]
revised examples

    manage PDUs; examples:
        rhubarbe-pdu list               # summary, lists the known PDUs by name - static info only
        rhubarbe-pdu list anechoic      # here anechoic is the name of a pdu_host
                                        # here again it's a static info
        rhubarbe-pdu list jaguar        # works with devices too
                                        # static info only (no network needed)

        rhubarbe-pdu status anechoic    # this time the PDU is probed for a detailed view of the PDU
        rhubarbe-pdu status x310        # here x310, jaguar, and n300 are device names

        rhubarbe-pdu on jaguar
        rhubarbe-pdu off panther
        rhubarbe-pdu reset n300

**Comment by parmentelat** [comment]
as of 5.2.1 we have some of this available, i.e. the `script` subcommand has gone and one can obtain/set an individual status using `rhubarbe-pdu status|on|off|reset`
the monitoring however still needs more work, although the logic seems fine, it could be that several ssh simultaneous connections just can't fly with these boxes
so truly snmp looks like the right way to go as far as frequent monitoring is concerned

**Comment by parmentelat** [comment]
as of 5.2.6:

* the monitoring is done with SNMP only; can still be improved (particularly when probing a whole PDU) but it's **much** faster than the ssh version
* actually controlling the outlet states is still done using ssh; this too can probably be simplified to remove the use of expect

**Comment by parmentelat** [comment]
good enough for now, closing
